package main

//
// a word-count application "plugin" for MapReduce.
//
// go build -buildmode=plugin wc.go
//

import (
	"strconv"
	"strings"
	"unicode"

	"6.824/mr"
)

// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
func Map(filename string, contents string) []mr.KeyValue {
	// function to detect word separators.
	ff := func(r rune) bool { return !unicode.IsLetter(r) }
	/* 定义一个用于判断分隔符的 lambda 函数，并存进变量 ff
		输入：rune 输出：bool
		这是一个匿名函数
		正常函数：
		func isSeparator(r rune) bool {
	    return !unicode.IsLetter(r)
		}
		有点类似于java的 lambda 表达式，Go 通过匿名函数来实现类似的功能。匿名函数可以直接在需要函数的地方定义和使用，而不需要为它命名。这使得代码更加简洁和灵活。
		Predicate<Character> ff =
	    c -> !Character.isLetter(c);


	*/

	// split contents into an array of words.
	words := strings.FieldsFunc(contents, ff)

	kva := []mr.KeyValue{}
	for _, w := range words {
		kv := mr.KeyValue{w, "1"}
		kva = append(kva, kv)
	}
	return kva
}

// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
func Reduce(key string, values []string) string {
	// return the number of occurrences of this word.
	return strconv.Itoa(len(values))
}

/*
-buildmode=plugin 说明这不是 executable，这是这是 plugin 不需要main（），编译后会生成一个 .so 文件，可以被其他 Go 程序动态加载和调用。
类似于Java
class WordCountPlugin {
    public static Map(...)
    public static Reduce(...)
}
但是Go没有class，只有函数和类型，所以我们直接定义了两个函数 Map 和 Reduce，这些函数会被 MapReduce 框架调用。
package main
func Map()
func Reduce()

为什么 MIT 用 plugin？
因为真正的 MapReduce 框架必须：“框架”和“业务逻辑”分离
框架不知道：你要做 wordcount 还是 inverted index 还是 pagerank
所以用户提供：Map() Reduce()
*/

/*
wc.go 本质上是：“用户写给 MapReduce Framework 的业务插件”
框架：不知道怎么处理数据
用户提供：Map() Reduce()
然后：mrsequential.go 或者 worker动态加载并调用它们。
*/
